apiVersion: v1
description: Bookinfo details Service Helm Chart
name: bookinfo-details
version: 1.0.0
appVersion: 1.0.0
home: https://bookinfo.dev.opsta.net/student78/details
maintainers:
  - name: student78
    email: devop078@mail.kmutt.ac.th
sources:
  - https://github.com/wajanapnap/bookinfo-details